import { ShareData } from '@/types/api';

export const copyToClipboard = async (text: string) => {
  await navigator.clipboard.writeText(text);
};

export const formatTeamsForSharing = (data: ShareData) => {
  const { teams, matches, game } = data;
  
  let shareText = `🎮 ${game.toUpperCase()} TEAMS 🎮\n\n`;

  // Teams Section
  shareText += `👥 TEAMS:\n`;
  teams.forEach((team, index) => {
    shareText += `\n${index + 1}. ${team.name}\n`;
    team.players.forEach(player => {
      const isDoubleSided = team.doubleSidedPlayers?.includes(player);
      shareText += `   • ${player}${isDoubleSided ? ' (Double-sided)' : ''}\n`;
    });
  });

  // Matches Section
  if (matches.length > 0) {
    shareText += `\n📅 MATCH SCHEDULE:\n`;
    matches.forEach(match => {
      shareText += `\n⚔️ Match ${match.match}\n`;
      shareText += `   ${match.team1} vs ${match.team2}\n`;
      if (match.toss) {
        shareText += `   🎲 Toss Winner: ${match.toss}\n`;
      }
      shareText += `   ⏰ ${match.time}\n`;
    });
  }

  shareText += `\nGenerated by TeamGen`;
  return shareText;
};

export const shareTeams = async (data: ShareData) => {
  const shareText = formatTeamsForSharing(data);
  await copyToClipboard(shareText);
};

export const shareToWhatsApp = (data: ShareData) => {
  const shareText = formatTeamsForSharing(data);
  const encodedText = encodeURIComponent(shareText);
  window.open(`https://wa.me/?text=${encodedText}`, '_blank');
};

export const shareToInstagram = (data: ShareData) => {
  const shareText = formatTeamsForSharing(data);
  // Open in a new tab since Instagram doesn't have a direct sharing API
  const encodedText = encodeURIComponent(shareText);
  window.open(`https://www.instagram.com/direct/new/?text=${encodedText}`, '_blank');
};